### ISSUE TITLE
__main__.CouldNotFindFile: Debug file not found

### ISSUE THREAD

**Issue by beenhuang** [shadow/shadow#1437]
I tried to install shadow on the Fedora 32.
And When I type the "./set build --clean --test" command, the following error message appears.
what should I do?

[ 11%] Generating vdl-config.h
Traceback (most recent call last):
  File "/home/parallels/shadow/src/external/elf-loader/extract-system-config.py", line 205, in <module>
    main(sys.argv[1:])
  File "/home/parallels/shadow/src/external/elf-loader/extract-system-config.py", line 184, in main
    debug_filename = search_debug_file()
  File "/home/parallels/shadow/src/external/elf-loader/extract-system-config.py", line 129, in search_debug_file
    raise CouldNotFindFile('Debug file not found')
__main__.CouldNotFindFile: Debug file not found
make[2]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:81: src/external/elf-loader/vdl-config.h] Error 1
make[2]: *** Deleting file 'src/external/elf-loader/vdl-config.h'
make[1]: *** [CMakeFiles/Makefile2:373: src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
2021-06-15 22:23:06,796 [ERROR] Non-zero return code from make.

**Comment by robgjansen** [comment]
We just merged a major update to the main branch. Please pull the latest code and try again. You'll have to go through the installation guide again to make sure you have the necessary dependencies installed.

Technically, we currently support Fedora 33 and not 32, but hopefully it will still work for you on 32.
https://github.com/shadow/shadow/tree/main/docs
