### ISSUE TITLE
Crash when network graph file does not exist

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1459]
When the network graph file path given in the config file does not exist, shadow crashes. I would expect a warning or error message and a clean exit.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', core/support/configuration.rs:1329:
83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Shadow version:
```
shadow --show-build-info
Shadow v2.0.0-pre.1-29-gd2c7909 running GLib v2.56.1 and IGraph v0.7.1
Shadow was built from branch determinism on 2021-06-17--17:10:19 in Release mode with compile options: -ggdb;-fno-omit-frame-pointer;-Wreturn-type;-Wswitch;-O3 and link options: -Wl,--no-as-needed
```

Stack trace:

```gdb
0x00007f6d10a0d3d7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f6d10a0d3d7 in raise () from /lib64/libc.so.6
#1  0x00007f6d10a0eac8 in abort () from /lib64/libc.so.6
#2  0x000000000079cdb7 in std::sys::unix::abort_internal::h62d932bf0be45017 () at library/std/src/sys/unix/mod.rs:237
#3  0x0000000000789395 in std::sys_common::util::abort::h654366703a8a74b7 (args=...) at library/std/src/sys_common/util.rs:19
#4  0x000000000078b6ee in rust_panic (msg=...) at library/std/src/panicking.rs:642
#5  0x000000000078b557 in std::panicking::rust_panic_with_hook::h263160f22b059048 (payload=..., message=..., location=<optimized out>) at library/std/src/panicking.rs:610
#6  0x000000000078b017 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::hd45fe6038bd32735 () at library/std/src/panicking.rs:497
#7  0x000000000078711c in std::sys_common::backtrace::__rust_end_short_backtrace::h4fa0386d891c718a (f=...) at library/std/src/sys_common/backtrace.rs:141
#8  0x000000000078af79 in rust_begin_unwind (info=0x7ffdad213b28) at library/std/src/panicking.rs:493
#9  0x00000000007f5771 in core::panicking::panic_fmt::hb045f52f112433cc (fmt=...) at library/core/src/panicking.rs:92
#10 0x00000000007f53e3 in core::option::expect_none_failed::hadad17f061c76fec (msg=..., value=...) at library/core/src/option.rs:1329
#11 0x00000000005795f9 in config_getNetworkGraph ()
#12 0x00000000004cf6a8 in _controller_loadTopology (controller=0xe99af0) at /scratch/rjansen/phantom/code/shadow-phantom/src/main/core/controller.c:161
#13 controller_run (controller=0xe99af0) at /scratch/rjansen/phantom/code/shadow-phantom/src/main/core/controller.c:343
#14 0x00000000004cee25 in _main_helper (argv=<optimized out>, config=0xe87210, options=0xd4f640) at /scratch/rjansen/phantom/code/shadow-phantom/src/main/core/main.c:109
#15 main_runShadow (argc=<optimized out>, argv=<optimized out>) at /scratch/rjansen/phantom/code/shadow-phantom/src/main/core/main.c:277
#16 0x00007f6d109f9555 in __libc_start_main () from /lib64/libc.so.6
#17 0x00000000004ce694 in _start ()
(gdb) frame 11
#11 0x00000000005795f9 in config_getNetworkGraph ()
```

**Comment by stevenengler** [comment]
This seems to be fixed now with the new rust graph parsing code. When providing an incorrect network graph path, the output is currently:

```text
00:00:00.000001 [shadow] n/a [WARN] [n/a] [main.rs:81] [shadow_rs::core::main] Log level set to TRACE, but messages higher than DEBUG have been compiled out
00:00:00.000518 [shadow] n/a [DEBUG] [n/a] [shmem_cleanup.c:156] [shmemcleanup_tryCleanup] Num. removed shared memory files: 0
00:00:00.024703 [shadow] n/a [DEBUG] [n/a] [main.rs:113] [shadow_rs::core::main] ASLR disabled for processes forked from this parent process
00:00:00.024716 [shadow] n/a [INFO] [n/a] [main.c:68] [main_logBuildInfo] Starting Shadow v2.0.0-pre.4-191-gdc78b335-dirty 2021-09-13--14:41:53 with GLib v2.64.6
** Starting Shadow v2.0.0-pre.4-191-gdc78b335-dirty 2021-09-13--14:41:53 with GLib v2.64.6
00:00:00.024769 [shadow] n/a [INFO] [n/a] [main.c:72] [main_logBuildInfo] Shadow was built from branch main on 2021-09-13--18:57:26 in Release mode with compile options: -ggdb;-fno-omit-frame-pointer;-Wreturn-type;-Wswitch;-O3 and link options: -Wl,--no-as-needed
00:00:00.024772 [shadow] n/a [INFO] [n/a] [main.c:73] [main_logBuildInfo] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.024772 [shadow] n/a [INFO] [n/a] [main.c:74] [main_logBuildInfo] Logging current startup arguments and environment
00:00:00.024773 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: /shared/code/shadow/main/build/src/main/shadow
00:00:00.024774 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: -l
00:00:00.024774 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: trace
00:00:00.024775 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: --interpose-method
00:00:00.024775 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: preload
00:00:00.024776 [shadow] n/a [INFO] [n/a] [main.rs:207] [shadow_rs::core::main] arg: shadow.yaml
00:00:00.024783 [shadow] n/a [DEBUG] [n/a] [main.rs:127] [shadow_rs::core::main] Startup checks passed, we are ready to start the simulation
00:00:00.024785 [shadow] n/a [INFO] [n/a] [controller.c:103] [controller_new] simulation controller created
00:00:00.024786 [shadow] n/a [INFO] [n/a] [controller.c:428] [controller_run] loading and initializing simulation data
00:00:00.024793 [shadow] n/a [ERROR] [n/a] [network_graph.rs:644] [shadow_rs::routing::network_graph::export] No such file or directory (os error 2)
00:00:00.024855 [shadow] n/a [ERROR] [n/a] [controller.c:178] [_controller_loadNetworkGraph] fatal error loading graph, check your syntax and try again
00:00:00.024886 [shadow] n/a [INFO] [n/a] [controller.c:136] [controller_free] simulation controller destroyed
00:00:00.024909 [shadow] n/a [ERROR] [n/a] [main.rs:238] [shadow_rs::core::main::export] Controller exited with code 1
** Shadow did not complete successfully: Controller exited with code 1
** See the log for details
```
