### ISSUE TITLE
pidfd_open is not supported in kernel 4.15 on Ubuntu 18.04

### ISSUE THREAD

**Issue by marcosimioni** [shadow/shadow#1532]
**Describe the issue**
I'm on the latest commit `103814bfff08b7ddfb1960bc9e263dbaeb437ecc`, shadow is building fine but some tests are failing (list below).

The latest working commit on my machine seems to be https://github.com/shadow/shadow/commit/4730119f9d644d6b2fcecb0fc190e245e4f6a3f7 and tests start failing on https://github.com/shadow/shadow/commit/022d3bf156ec434486660c3de081676f8c3e352e (and intermediate commits with slightly different behaviors, but those were WIP commits I guess).

Looking at https://github.com/shadow/shadow/runs/3129268581?check_suite_focus=true, I see that the CI is on `kernel 5.8.0-1036-azure`, while my machine is on kernel `4.15.0-137-generic`. Do you think that might be the root issue with those changes?

Or, by looking at the tests below, do you have any pointer?

```
64% tests passed, 58 tests failed out of 159                                             
                                                                                         
Total Test time (real) =  24.70 sec                                                      
                                                                                         
The following tests FAILED:                                                              
          1 - tsc_test (Failed)                                                          
          3 - rust-unit-tests (Timeout)                                                  
          6 - bindc-shadow-preload (Failed)                                              
         11 - config-stdin-shadow-preload (Failed)                                       
         14 - cpp-shadow-preload (Failed)                                                
         18 - determinism1a-shadow-preload (Failed)                                      
         19 - determinism1b-shadow-preload (Failed)                                      
         20 - determinism1-compare-shadow-preload (Failed)                               
         24 - determinism2a-shadow-preload (Failed)                                      
         25 - determinism2b-shadow-preload (Failed)                                      
         26 - determinism2-shadow-preload-compare (Failed)                               
         28 - environment-shadow-preload (Failed)                                        
         31 - epoll-shadow-preload (Failed)                                              
         33 - epoll-writeable-shadow-preload (Failed)  
         36 - eventfd-shadow-preload (Failed)                  
         39 - exit-shadow-preload (Failed)                      
         42 - file-shadow-preload (Failed)                     
         45 - futex-shadow-preload (Failed)                     
         48 - ifaddrs-shadow-preload (Failed)               
         51 - mmap-shadow-preload (Failed)                   
         54 - unaligned-shadow-preload (Failed)                                          
         56 - phold-serial-shadow-preload (Failed)                                       
         58 - phold-parallel-shadow-preload (Failed)                                     
         60 - phold-rr-qdisc-shadow-preload (Failed)                                     
         63 - pipe-shadow-preload (Failed)                                               
         66 - poll-shadow-preload (Failed)                                               
         69 - random-shadow-preload (Failed)                                             
         76 - sleep-shadow-preload (Failed)                                              
         79 - sockbuf-shadow-preload (Failed)                                            
         82 - socket-shadow-preload (Failed)                                             
         85 - bind-shadow-preload (Failed)                                               
         87 - bind_in_new_process-shadow-preload (Failed)                                
         90 - listen-shadow-preload (Failed)                                             
         93 - getsockname-shadow-preload (Failed)                                        
         96 - accept-shadow-preload (Failed)                                             
         99 - connect-shadow-preload (Failed)                                            
        102 - getpeername-shadow-preload (Failed)                                        
        105 - socketpair-shadow-preload (Failed)                                         
        108 - shutdown-shadow-preload (Failed)                                           
        111 - sendto-recvfrom-shadow-preload (Failed)                                    
        114 - sockopt-shadow-preload (Failed)                                            
        117 - ioctl-shadow-preload (Failed)                                              
        120 - tcp-blocking-loopback-shadow-preload (Failed)                              
        122 - tcp-blocking-lossless-shadow-preload (Failed)                              
        124 - tcp-blocking-lossy-shadow-preload (Failed)                                 
        127 - tcp-nonblocking-poll-loopback-shadow-preload (Failed)                      
        129 - tcp-nonblocking-poll-lossless-shadow-preload (Failed)                      
        131 - tcp-nonblocking-poll-lossy-shadow-preload (Failed)                         
        134 - tcp-nonblocking-epoll-loopback-shadow-preload (Failed)                     
        136 - tcp-nonblocking-epoll-lossless-shadow-preload (Failed)                     
        138 - tcp-nonblocking-epoll-lossy-shadow-preload (Failed)                        
        141 - pthreads-shadow-preload (Failed)                                           
        144 - threads-noexit-shadow-preload (Failed)                                     
        147 - threads-group-leader-exits-shadow-preload (Failed)                         
        150 - timerfd-shadow-preload (Failed)                                            
        153 - udp-shadow-preload (Failed)                                                
        156 - udp-uniprocess-shadow-preload (Failed)                                     
        159 - unistd-shadow-preload (Failed)                                             
```

**To Reproduce**
Steps to reproduce the behavior. If you problem involves a simulation, please include the configuration file that you used.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
`Description:    Ubuntu 18.04.5 LTS`
 - Kernel version: post the output of `uname -a`  
`Linux <redacted> 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
`commit 103814bfff08b7ddfb1960bc9e263dbaeb437ecc`
 - Which plug-ins you are using:  
just building shadow

**Additional context**

**Comment by stevenengler** [comment]
Thanks for the bug report. We do support 18.04, but we're not able to test with different kernel versions in the GitHub CI unfortunately. If it is a kernel issue, Ubuntu provides kernel 5.4 for 18.04 if you enable HWE.

Can you attach the logs for one of the tests? For example if you run `./setup test environment-shadow-preload`, can you include the files `build/Testing/Temporary/LastTest.log` and `build/src/test/environment/environment-shadow-preload.data/hosts/testnode/testnode.test_env.1000.stdout`? If the logs are too long, you can upload them [here](https://paste.debian.net/) and post the link.

**Comment by marcosimioni** [comment]
@stevenengler sorry I was updating the issue description while you commented. I think I've identified the commits that introduced this issue.

let me dig the log for you.

**Comment by marcosimioni** [comment]
@stevenengler 

```
cat build/Testing/Temporary/LastTest.log

Start testing: Jul 22 16:44 IST
----------------------------------------------------------
28/159 Testing: environment-shadow-preload
28/159 Test: environment-shadow-preload
Command: "/bin/sh" "-c" "         rm -rf environment-shadow-preload.data          && /home/redacted/tor/shadow/build/src/main/shadow          --data-directory=environment-shadow-preload.data          --interpose-method=preload          --log-level=info          --use-cpu-pinning false          /home/redacted/tor/shadow/src/test/environment/environment.yaml          && (cd environment-shadow-preload.data && true)          "
Directory: /home/redacted/tor/shadow/build/src/test/environment
"environment-shadow-preload" start time: Jul 22 16:44 IST
Output:
----------------------------------------------------------
** Starting Shadow v2.0.0-pre.4-1-g103814bf 2021-07-21--19:44:24 with GLib v2.56.4 and IGraph v0.7.1
00:00:00.000001 [shadow] n/a [INFO] [n/a] [disable_aslr.c:14] [disable_aslr] ASLR disabled for processes forked from this parent process.
00:00:00.000049 [shadow] n/a [INFO] [n/a] [main.c:89] [_main_helper] Starting Shadow v2.0.0-pre.4-1-g103814bf 2021-07-21--19:44:24 with GLib v2.56.4 and IGraph v0.7.1
00:00:00.000123 [shadow] n/a [INFO] [n/a] [main.c:96] [_main_helper] Shadow was built from branch HEAD on 2021-07-22--16:43:52 in Release mode with compile options: -ggdb;-fno-omit-frame-pointer;-Wreturn-type;-Wswitch;-O3 and link options: -Wl,--no-as-needed
00:00:00.000125 [shadow] n/a [INFO] [n/a] [main.c:97] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000126 [shadow] n/a [INFO] [n/a] [main.c:98] [_main_helper] logging current startup arguments and environment
00:00:00.000131 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: /home/redacted/tor/shadow/build/src/main/shadow
00:00:00.000132 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: --data-directory=environment-shadow-preload.data
00:00:00.000134 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: --interpose-method=preload
00:00:00.000135 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: --log-level=info
00:00:00.000136 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: --use-cpu-pinning
00:00:00.000136 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: false
00:00:00.000137 [shadow] n/a [INFO] [n/a] [main.c:42] [_main_logEnvironment] arg: /home/redacted/tor/shadow/src/test/environment/environment.yaml
00:00:00.000140 [shadow] n/a [INFO] [n/a] [main.c:104] [_main_helper] startup checks passed, we are ready to start simulation
00:00:00.000143 [shadow] n/a [INFO] [n/a] [controller.c:102] [controller_new] simulation controller created
00:00:00.000143 [shadow] n/a [INFO] [n/a] [controller.c:343] [controller_run] loading and initializing simulation data
00:00:00.000263 [shadow] n/a [INFO] [n/a] [topology.c:346] [_topology_loadGraph] reading gml topology graph at '/tmp/shadow-topology-KRWM60.gml'...
00:00:00.000393 [shadow] n/a [INFO] [n/a] [topology.c:357] [_topology_loadGraph] successfully read gml topology graph at '/tmp/shadow-topology-KRWM60.gml'
00:00:00.000398 [shadow] n/a [INFO] [n/a] [topology.c:663] [_topology_checkGraphProperties] checking graph properties...
00:00:00.000399 [shadow] n/a [INFO] [n/a] [topology.c:530] [_topology_checkGraphAttributes] checking graph attributes...
00:00:00.000409 [shadow] n/a [INFO] [n/a] [topology.c:651] [_topology_checkGraphAttributes] successfully verified all graph, vertex, and edge attributes
00:00:00.000427 [shadow] n/a [INFO] [n/a] [topology.c:704] [_topology_checkGraphProperties] topology graph is complete, undirected, and strongly connected with 1 cluster. It uses shortest paths.
00:00:00.000428 [shadow] n/a [INFO] [n/a] [topology.c:873] [_topology_checkGraphVertices] checking graph vertices...
00:00:00.000612 [shadow] n/a [INFO] [n/a] [topology.c:887] [_topology_checkGraphVertices] 1 graph vertices ok
00:00:00.000616 [shadow] n/a [INFO] [n/a] [topology.c:1021] [_topology_checkGraphEdges] checking graph edges...
00:00:00.000686 [shadow] n/a [INFO] [n/a] [topology.c:1035] [_topology_checkGraphEdges] 1 graph edges ok
00:00:00.000692 [shadow] n/a [INFO] [n/a] [topology.c:1056] [_topology_checkGraph] successfully parsed gml and validated topology: graph is strongly connected with 1 cluster, 1 vertex, and 1 edge
00:00:00.000831 [shadow] n/a [INFO] [n/a] [manager.c:206] [manager_new] found required preload library libshadow-shim.so at path /home/redacted/tor/shadow/build/src/lib/shim/libshadow-shim.so
00:00:00.000848 [shadow] n/a [INFO] [n/a] [manager.c:215] [manager_new] found optional preload library libshadow_openssl_rng.so at path /home/redacted/tor/shadow/build/src/lib/openssl_preload/libshadow_openssl_rng.so
00:00:00.001096 [shadow] n/a [INFO] [n/a] [scheduler.c:179] [scheduler_new] main scheduler thread will operate with 1 worker threads
00:00:00.001185 [shadow] n/a [INFO] [n/a] [controller.c:363] [controller_run] registering plugins and hosts
00:00:00.001199 [shadow] n/a [INFO] [n/a] [host.c:134] [host_new] Created host id '2' name 'testnode'
00:00:00.001272 [shadow] n/a [INFO] [n/a] [topology.c:2271] [topology_attach] attached address '11.0.0.1' to vertex 0 ('0') with attributes (ip=0.0.0.0, citycode=(null), countrycode=(null)) using hints (ip=(null), citycode=(null), countrycode=(null))
00:00:00.001289 [shadow] n/a [INFO] [n/a] [host.c:212] [host_setup] Setup host id '2' name 'testnode' with seed 1105148392, ip 11.0.0.1, 122070 bwUpKiBps, 122070 bwDownKiBps, 131072 initSockSendBufSize, 174760 initSockRecvBufSize, 2500000 cpuFrequency, 0 cpuThreshold, 200 cpuPrecision
00:00:00.001336 [shadow] n/a [INFO] [n/a] [controller.c:369] [controller_run] running simulation
00:00:00.001340 [shadow] n/a [INFO] [n/a] [controller.c:373] [controller_run] log message buffering is enabled for efficiency
00:00:00.001373 [worker-0] n/a [INFO] [n/a] [scheduler.c:70] [_scheduler_startHostsWorkerTaskFn] starting to boot 1 hosts
00:00:00.001418 [worker-0] 00:00:00.000000000 [INFO] [testnode:11.0.0.1] [tracker.c:430] [_tracker_logNode] [shadow-heartbeat] [node-header] interval-seconds,recv-bytes,send-bytes,cpu-percent,delayed-count,avgdelay-milliseconds;inbound-localhost-counters;outbound-localhost-counters;inbound-remote-counters;outbound-remote-counters where counters are: packets-total,bytes-total,packets-control,bytes-control-header,packets-control-retrans,bytes-control-header-retrans,packets-data,bytes-data-header,bytes-data-payload,packets-data-retrans,bytes-data-header-retrans,bytes-data-payload-retrans
00:00:00.001455 [worker-0] 00:00:00.000000000 [INFO] [testnode:11.0.0.1] [tracker.c:456] [_tracker_logNode] [shadow-heartbeat] [node] 1,0,0,0.000000,0,0.000000;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0
00:00:00.001485 [worker-0] n/a [INFO] [n/a] [scheduler.c:72] [_scheduler_startHostsWorkerTaskFn] 1 hosts are booted
00:00:00.001590 [worker-0] 00:00:01.000000000 [INFO] [testnode:11.0.0.1] [tracker.c:456] [_tracker_logNode] [shadow-heartbeat] [node] 1,0,0,0.000000,0,0.000000;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0
00:00:00.001768 [worker-0] 00:00:01.000000000 [INFO] [testnode:11.0.0.1] [process.c:497] [_process_start] starting process 'testnode.test_env.1000'
00:00:00.002040 [worker-0] 00:00:01.000000000 [INFO] [testnode:11.0.0.1] [thread_preload.c:178] [threadpreload_run] forking new thread with environment 'SHADOW_SPAWNED=TRUE SHADOW_LOG_START_TIME=811953053364 SHADOW_INTERPOSE_METHOD=PRELOAD TESTING_ENV_VAR_1=HELLO WORLD TESTING_ENV_VAR_2=SOMETHING LD_PRELOAD=/home/redacted/tor/shadow/build/src/lib/shim/libshadow-shim.so:/home/redacted/tor/shadow/build/src/lib/openssl_preload/libshadow_openssl_rng.so:/my/custom/ld/preload/path.so SHADOW_LOG_FILE=/home/redacted/tor/shadow/build/src/test/environment/environment-shadow-preload.data/hosts/testnode/testnode.test_env.1000.shimlog SHADOW_IPC_BLK=8,134217728,648,/shadow_shmemfile_811953.55142897-7001 SHADOW_USE_SECCOMP= SHADOW_PID=7001', arguments '/home/redacted/tor/shadow/build/src/test/target/debug/test_env', and working directory '/home/redacted/tor/shadow/build/src/test/environment/environment-shadow-preload.data/hosts/testnode'
thread '<unnamed>' panicked at 'pidfd_open: ENOSYS', utility/childpid_watcher.rs:183:17
stack backtrace:
ERROR: ld.so: object '/my/custom/ld/preload/path.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: shadow_rs::utility::childpid_watcher::ChildPidWatcher::watch
   3: threadpreload_run
             at /home/redacted/tor/shadow/src/main/host/thread_preload.c:183
   4: thread_run
             at /home/redacted/tor/shadow/src/main/host/thread.c:91
   5: _process_start
             at /home/redacted/tor/shadow/src/main/host/process.c:510
   6: _process_runStartTask
             at /home/redacted/tor/shadow/src/main/host/process.c:644
   7: event_execute
             at /home/redacted/tor/shadow/src/main/core/work/event.c:86
   8: worker_runEvent
             at /home/redacted/tor/shadow/src/main/core/worker.c:469
   9: _scheduler_runEventsWorkerTaskFn
             at /home/redacted/tor/shadow/src/main/core/scheduler/scheduler.c:86
  10: _worker_run
             at /home/redacted/tor/shadow/src/main/core/worker.c:440
  11: start_thread
  12: __clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
<end of output>
Test time =   0.28 sec
----------------------------------------------------------
Test Failed.
"environment-shadow-preload" end time: Jul 22 16:44 IST
"environment-shadow-preload" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jul 22 16:44 IST
```

**Comment by marcosimioni** [comment]
while `build/src/test/environment/environment-shadow-preload.data/hosts/testnode/testnode.test_env.1000.stdout` is empty

**Comment by stevenengler** [comment]
@sporksmith:

> thread '<unnamed>' panicked at 'pidfd_open: ENOSYS', utility/childpid_watcher.rs:183:17

What should we do about this syscall? Is there something else we can do for backwards compatibility? Or should we require everyone to enable hardware enablement to upgrade their kernel? This might not be possible for people who want to run shadow on shared systems.

@marcosimioni:

Thanks for the logs. You should still be able to use shadow fine in ptrace mode (the default mode). It's only the preload mode that is failing since the `pidfd_open` syscall isn't supported on your kernel.

**Comment by marcosimioni** [comment]
@stevenengler are you saying I can ignore these failing tests for now, and by default shadow will be running in ptrace mode and therefore it won't affect the simulations?

**Comment by stevenengler** [comment]
> @stevenengler are you saying I can ignore these failing tests for now, and by default shadow will be running in ptrace mode and therefore it won't affect the simulations?

Right, these failing tests are for a non-default mode ([preload mode](https://shadow.github.io/docs/guide/shadow_config_spec.html#experimentalinterpose_method)). Shadow in its default mode (ptrace mode) should run simulations fine and won't be affected by this bug.

**Comment by sporksmith** [comment]
> What should we do about this syscall? Is there something else we can do for backwards compatibility? Or should we require everyone to enable hardware enablement and upgrade their kernel? This might not be possible for people who want to run shadow on shared systems.

Hmm, bummer.

Given that ptrace mode still works, maybe we could live with not supporting preload mode on older kernels, though we should probably have a nicer failure mode that explains what's going on.

Another possibility might be to share a pipe with the child, where the child has the writer end, and detect when our reader end gets closed.

Let's chat about it in the dev meeting today.

**Comment by sporksmith** [comment]
AFAICT, pidfd_open was introduced in 5.3. https://news.softpedia.com/news/linux-kernel-5-3-officially-released-here-s-what-s-new-527410.shtml

**Comment by sporksmith** [comment]
Taking a stab at removing dependene on pidfd_open

**Comment by marcosimioni** [comment]
Tested on commit `b9c8b840d2a57a5e76ec9f45db5af571fdfac814`, all good!

All tests pass (well, apart from https://github.com/shadow/shadow/issues/1519), thank you all for your work on this.
