### ISSUE TITLE
Infinite loops during shutdown

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#200]
I've noticed several times that occasionally there are infinite loops in the glib hashtable destroy function while shadow is attempting to free resources and shut down. This should be tracked down and fixed.

**Comment by robgjansen** [comment]
I believe there is an error in GLib's hash table.
https://bugzilla.gnome.org/show_bug.cgi?id=694501

My problem ocured in the while loop starting here:
```
555           while (!HASH_IS_UNUSED (new_hashes[hash_val]))
(gdb) bt
#0  0x0000003fd8a37eea in g_hash_table_resize (hash_table=hash_table@entry=0x17ae920 = {...}) at ghash.c:555
#1  0x0000003fd8a382d7 in g_hash_table_maybe_resize (hash_table=0x17ae920 = {...}) at ghash.c:597
#2  g_hash_table_remove_internal (hash_table=0x17ae920 = {...}, key=0x17c7ee0, notify=1) at ghash.c:1301
#3  0x000000000044e9a8 in dns_deregister (dns=0x17ae540, address=0x17c7d50) at /home/rob/dev/shadow/src/topology/shd-dns.c:142
#4  0x000000000043fcfc in networkinterface_free (interface=0x17c8450) at /home/rob/dev/shadow/src/host/shd-network-interface.c:130
#5  0x0000003fd8a38107 in g_hash_table_remove_all_nodes (hash_table=0x17c6e40, notify=<optimized out>) at ghash.c:503
#6  0x0000003fd8a38e9a in g_hash_table_remove_all (hash_table=0x17c6e40) at ghash.c:1371
#7  0x0000003fd8a38f0e in g_hash_table_destroy (hash_table=0x17c6e40) at ghash.c:1067
#8  0x000000000043b0c6 in host_free (host=0x17c7c40, userData=0x0) at /home/rob/dev/shadow/src/host/shd-host.c:174
#9  0x0000003fd8a45d9d in g_list_foreach (list=<optimized out>, func=0x43aff0 <host_free>, user_data=0x0) at glist.c:994
#10 0x0000000000416800 in worker_runParallel (workload=0x7fffbc12a060) at /home/rob/dev/shadow/src/engine/shd-worker.c:219
#11 0x0000003fd8a703d5 in g_thread_proxy (data=0x1891000) at gthread.c:764
#12 0x0000003fd660752a in start_thread (arg=0x7fc896355700) at pthread_create.c:310
#13 0x0000003fd5f0022d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The full while loop is:

```
555           while (!HASH_IS_UNUSED (new_hashes[hash_val]))
556             {
557               step++;
558               hash_val += step;
559               hash_val &= hash_table->mask;
560             }
```

**Comment by robgjansen** [comment]
I haven't been able to reproduce this recently. Please re-open if the issue is identified again.
