### ISSUE TITLE
CTasks are dropped/freed when their owning host lock isn't held

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2152]
`CTask` objects hold the host ID for the host that their `object` and `argument` fields belong to. Those fields should only be accessed when that host lock is held, and the `CTask` checks this by using `Worker::with_active_host_info()` to compare its host ID to the global host ID.

The `worker_sendPacket()` function creates a new `Event` for each packet and schedules them with `scheduler_push()`. If the event time is after the simulation end time, the scheduler will unref that `Event`, causing the `TaskRef` to be dropped and calling the `CTask`s `object_free` and `argument_free` functions. Since the packet event is intended for a different host than the currently running host, this causes a panic in debug builds since the task's host ID doesn't match the currently running host ID.

This backtrace is from a tor minimal simulation (shadow built in debug mode). The shadow network latency was changed from "50 ms" to "200 ms".

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `HostId(7)`,
 right: `HostId(3)`', main/core/work/task.rs:106:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:182:5
   4: shadow_rs::core::work::task::export::CTask::check_host_id::{{closure}}
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/task.rs:106:17
   5: core::option::Option<T>::map
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:906:29
   6: shadow_rs::core::worker::Worker::with_active_host_info::{{closure}}
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.rs:110:26
   7: shadow_rs::core::worker::Worker::with::{{closure}}::{{closure}}
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.rs:239:43
   8: core::option::Option<T>::map
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:906:29
   9: shadow_rs::core::worker::Worker::with::{{closure}}
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.rs:239:27
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  11: shadow_rs::core::worker::Worker::with
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.rs:238:9
  12: shadow_rs::core::worker::Worker::with_active_host_info
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.rs:110:9
  13: shadow_rs::core::work::task::export::CTask::check_host_id
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/task.rs:105:13
  14: <shadow_rs::core::work::task::export::CTask as core::ops::drop::Drop>::drop
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/task.rs:122:13
  15: core::ptr::drop_in_place<shadow_rs::core::work::task::export::CTask>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  16: core::ptr::drop_in_place<shadow_rs::core::work::task::export::taskref_new::{{closure}}>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  17: core::ptr::drop_in_place<core::cell::UnsafeCell<dyn core::ops::function::FnMut<(&mut shadow_rs::host::host::Host,)>+Output = ()+core::marker::Send+core::
marker::Sync>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  18: core::ptr::drop_in_place<atomic_refcell::AtomicRefCell<dyn core::ops::function::FnMut<(&mut shadow_rs::host::host::Host,)>+Output = ()+core::marker::Send
+core::marker::Sync>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  19: alloc::sync::Arc<T>::drop_slow
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/sync.rs:1092:18
  20: <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/sync.rs:1688:13
  21: core::ptr::drop_in_place<alloc::sync::Arc<atomic_refcell::AtomicRefCell<dyn core::ops::function::FnMut<(&mut shadow_rs::host::host::Host,)>+Output = ()+core::marker::Send+core::marker::Sync>>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  22: core::ptr::drop_in_place<shadow_rs::core::work::task::TaskRef>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  23: core::ptr::drop_in_place<alloc::boxed::Box<shadow_rs::core::work::task::TaskRef>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
  24: taskref_drop
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/task.rs:187:39
  25: _event_free
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/event.c:44:5
  26: event_unref
             at /shared/code/shadow/improve-sigkill-check/src/main/core/work/event.c:59:9
  27: scheduler_push
             at /shared/code/shadow/improve-sigkill-check/src/main/core/scheduler/scheduler.c:236:9
  28: worker_sendPacket
             at /shared/code/shadow/improve-sigkill-check/src/main/core/worker.c:594:9
  29: router_forward
             at /shared/code/shadow/improve-sigkill-check/src/main/routing/router.c:100:5
  30: _networkinterface_sendPackets
             at /shared/code/shadow/improve-sigkill-check/src/main/host/network_interface.c:601:13
  31: networkinterface_wantsSend
             at /shared/code/shadow/improve-sigkill-check/src/main/host/network_interface.c:652:5
  32: legacysocket_addToOutputBuffer
             at /shared/code/shadow/improve-sigkill-check/src/main/host/descriptor/socket.c:463:5
...
```

**Comment by sporksmith** [comment]
IIRC the object being sent in this case is a "deep clone" of a packet, which may be safe for any host to deallocate. I don't think it's worth further complicating the types here to express this, though.

The simplest thing I can think of is scheduling a no-op task in this case, with the provided objects and destructors. The correct host would then execute the no-op callback, followed by the destructors.

We could alternatively add an escape hatch like `taskref_unsafe_unchecked_drop` or something, but I don't think it's worth it vs just safely scheduling a task, since this should be infrequent.

**Comment by sporksmith** [comment]
> The simplest thing I can think of is scheduling a no-op task in this case, with the provided objects and destructors. The correct host would then execute the no-op callback, followed by the destructors.

Actually that'd require mutating the TaskRef, which we currently don't support. Probably simpler to create a new TaskRef that takes the previous TaskRef as the object. e.g. something like:

`taskref_new(dst_host, taskref_drop, task_to_drop, NULL, NULL, NULL)`
