### ISSUE TITLE
Memory manager panic in `copy_into_file`

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2482]
When running a small simulation, I get the following panic in every worker thread. This seems to happen after the plugin process fails due to a segfault, but we probably shouldn't panic here anyways, even if the plugin previously failed.

```text
thread 'shadow-worker' panicked at 'called `Result::unwrap()` on an `Err` value: EFAULT', main/host/memory_manager/memory_mapper.rs:156:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: shadow_rs::host::memory_manager::memory_mapper::ShmFile::copy_into_file
   4: shadow_rs::host::memory_manager::memory_mapper::MemoryMapper::new
   5: shadow_rs::host::memory_manager::MemoryManager::init_mapper
   6: memorymanager_initMapperIfNeeded
   7: syscallhandler_shadow_init_memory_manager
             at ./shadow/src/main/host/syscall/shadow.c:115:9
   8: syscallhandler_make_syscall
             at ./shadow/src/main/host/syscall_handler.c:410:13
   9: managedthread_resume
             at ./shadow/src/main/host/managed_thread.c:301:40
  10: thread_resume
             at ./shadow/src/main/host/thread.c:125:30
  11: process_continue
             at ./shadow/src/main/host/process.c:696:5
  12: process_continue
             at ./shadow/src/main/host/process.c:672:6
  13: _process_start
             at ./shadow/src/main/host/process.c:630:5
  14: shadow_rs::core::work::event::Event::execute
  15: event_executeAndFree
  16: host_execute
             at ./shadow/src/main/host/host.c:427:9
  17: shadow_rs::core::scheduler::thread_per_core::SchedulerScope::run_with_data::{{closure}}
  18: shadow_rs::core::scheduler::pools::unbounded::work_loop
```

```bash
g++ -std=c++11 -march=native -O2 -Wall
```

```cpp
#define _POSIX_C_SOURCE 200809L
#include <unistd.h>

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <random>

int main(int argc, char **argv) {
  unsigned int x = 5;

  std::random_device rd;
  std::mt19937 rng(rd());
  std::uniform_int_distribution<int> uni(-x/2, x/2);

  auto y = uni(rng);
  std::printf("%d\n", y);

  return 0;
}
```

```yaml
general:
  stop_time: 99999 hours
  model_unblocked_syscall_latency: true

network:
  graph:
    type: 1_gbit_switch

hosts:
  client:
    network_node_id: 0
    quantity: 2000
    processes:
    - path: ./bin
      start_time: 1s
```

**Comment by sporksmith** [comment]
I think has been fixed for some time. I ran with and without --memeory-manager, and shadow correctly reports the child exiting with SIGSEGV, without itself panicking.

```
$ shadow-exec --shadow-arg="--use-memory-manager=false" -- ./a.out 
Traceback (most recent call last):
  File "/home/jnewsome/.local/bin/shadow-exec", line 8, in <module>
    sys.exit(__main__())
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 389, in __main__
    _main(
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 304, in _main
    run_shadow_watching_process(
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 259, in run_shadow_watching_process
    raise Exception(
Exception: shadow exited with code 1. stderr:
** Starting Shadow 3.3.0
Error: process 'host.dash.1000' exited with status Signaled(Signal(11)); expected end state was exited: 0 but was signaled: SIGSEGV
Error: Failed to run the simulation
Error: 
Error: Caused by:
Error:     1 managed processes in unexpected final state
** Shadow did not complete successfully: Failed to run the simulation
**   1 managed processes in unexpected final state
** See the log for details
```

```
$ shadow-exec --shadow-arg="--use-memory-manager=true" -- ./a.out 
Traceback (most recent call last):
  File "/home/jnewsome/.local/bin/shadow-exec", line 8, in <module>
    sys.exit(__main__())
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 389, in __main__
    _main(
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 304, in _main
    run_shadow_watching_process(
  File "/home/jnewsome/projects/shadow/shadowtools/src/shadowtools/shadow_exec.py", line 259, in run_shadow_watching_process
    raise Exception(
Exception: shadow exited with code 1. stderr:
** Starting Shadow 3.3.0
Error: process 'host.dash.1000' exited with status Signaled(Signal(11)); expected end state was exited: 0 but was signaled: SIGSEGV
Error: Failed to run the simulation
Error: 
Error: Caused by:
Error:     1 managed processes in unexpected final state
** Shadow did not complete successfully: Failed to run the simulation
**   1 managed processes in unexpected final state
** See the log for details
```
