### ISSUE TITLE
Fix sporadic "getsockname-linux" test failures

### ISSUE THREAD

**Issue by haxxpop** [shadow/shadow#2491]
**Describe the issue**
The test of `getsockname-linux` _sometimes_ fails

**To Reproduce**
- Checkout the branch of `v2.2.0`
- Build the project `./setup build --test`
- Run the test `./setup test`

Note that the test of `getsockname-linux` fails only sometimes, so you probably need to run `./setup test` a few times.

**Operating System (please complete the following information):**
 - OS and version: Ubuntu 20.04.5 LTS
 - Kernel version: Linux thinkpad-t14-g2 5.14.0-1052-oem # 59-Ubuntu SMP Fri Sep 9 09:37:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 

**Shadow (please complete the following information):**
 - Version: Shadow v2.2.0-0-ge36f6582 2022-07-19--16:42:14
 - Which plug-ins you are using:  

**Additional context**
The log is shown here https://pastebin.com/AZcuQtVi

**Comment by stevenengler** [comment]
Can you run `./setup test getsockname-linux` until it fails, and then add here the output of `build/Testing/Temporary/LastTest.log`?

But yeah sometimes the Linux-only test fail sporadically depending on what else is running on your system at the time. As long as the `-shadow` tests pass, Shadow should be working fine.

**Comment by ppopth** [comment]
```
cat build/Testing/Temporary/LastTest.log
Start testing: Oct 26 00:05 +07
----------------------------------------------------------
81/131 Testing: getsockname-linux
81/131 Test: getsockname-linux
Command: "/usr/bin/sh" "-c" "../../target/debug/test_getsockname --libc-passing"
Directory: /home/pop/repos/shadow/shadow/build/src/test/socket/getsockname
"getsockname-linux" start time: Oct 26 00:05 +07
Output:
----------------------------------------------------------
Testing test_invalid_fd... ✓
Testing test_non_existent_fd... ✓
Testing test_non_socket_fd... ✓
Testing test_short_len_inet... ✓
Testing test_unbound_socket <domain=2, sock_type=1>... ✓
Testing test_bound_socket <domain=2, sock_type=1>... ✓
Testing test_autobound_socket <domain=2, sock_type=1>... ✓
Testing test_after_close <domain=2, sock_type=1>... ✓
Testing test_bound_connected_socket <domain=2, sock_type=1>...thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `0`', test/socket/getsockname/test_getsockname.rs:634:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:181:5
   4: test_getsockname::test_bound_connected_socket
             at /home/pop/repos/shadow/shadow/src/test/socket/getsockname/test_getsockname.rs:634:9
   5: test_getsockname::get_tests::{{closure}}
             at /home/pop/repos/shadow/shadow/src/test/socket/getsockname/test_getsockname.rs:107:29
   6: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1886:9
   7: test_utils::ShadowTest<T,E>::run
             at /home/pop/repos/shadow/shadow/src/test/test_utils.rs:54:9
   8: test_utils::run_tests
             at /home/pop/repos/shadow/shadow/src/test/test_utils.rs:78:15
   9: test_getsockname::main
             at /home/pop/repos/shadow/shadow/src/test/socket/getsockname/test_getsockname.rs:39:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"getsockname-linux" end time: Oct 26 00:05 +07
"getsockname-linux" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Oct 26 00:05 +07

linux =   0.01 sec*proc

```

**Comment by stevenengler** [comment]
This failure means we were unable to bind an inet tcp socket to `localhost:1113`. This is the only test that uses this port, so either the OS assigned this port to another socket in some process (possibly this test), or the socket from a previous test run is still in TIME_WAIT state and we can't bind a new socket to that address.

Normally a test would let the OS assign an unused port number, but this test is explicitly testing the case where we manually bind a socket with a predetermined port before listening, so changing this would defeat the purpose of the test.

It would be nice if ctest had a "warn" state for linux tests instead of only "success" and "fail". I'm not sure what else we should do here.

**Comment by stevenengler** [comment]
I think we could wrap the program with `launch_with_unused_ports.py` here. It would complicate things a bit, but might be worthwhile.
