### ISSUE TITLE
MongoDB simulation fails

### ISSUE THREAD

**Issue by Congyu-Liu** [shadow/shadow#2674]
**Describe the issue**

shadow log:
```
00:00:00.057005 [2562641:shadow-worker] 00:00:00.000037280 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 27 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.057007 [2562641:shadow-worker] 00:00:00.000037280 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 27, which may result in unusual behavior
00:00:00.068151 [2562641:shadow-worker] 00:00:00.000047280 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 26 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.068153 [2562641:shadow-worker] 00:00:00.000047280 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 26, which may result in unusual behavior
00:00:00.122093 [2562641:shadow-worker] 00:00:00.000214290 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 95 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.122094 [2562641:shadow-worker] 00:00:00.000214290 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 95, which may result in unusual behavior
00:00:00.122184 [2562641:shadow-worker] 00:00:00.000214290 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 95 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.122186 [2562641:shadow-worker] 00:00:00.000214290 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 95, which may result in unusual behavior
00:00:00.125406 [2562641:shadow-worker] 00:00:00.000236350 [WARN] [server1:222.222.222.222] [socket.c:479] [_syscallhandler_setTCPOptHelper] setsockopt on level SOL_TCP called with unsupported option 23
00:00:00.125453 [2562641:shadow-worker] 00:00:00.000238350 [WARN] [server1:222.222.222.222] [socket.c:479] [_syscallhandler_setTCPOptHelper] setsockopt on level SOL_TCP called with unsupported option 30
00:00:00.136717 [2562641:shadow-worker] 00:00:00.000264460 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 435 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.136719 [2562641:shadow-worker] 00:00:00.000264460 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 435, which may result in unusual behavior
00:00:00.172444 [2562641:shadow-worker] 00:00:00.000271470 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 435 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.172446 [2562641:shadow-worker] 00:00:00.000271470 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 435, which may result in unusual behavior
00:00:00.204266 [2562641:shadow-worker] 00:00:00.000274460 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 128 called from thread 1001 in process server1.mongod.1000 on host server1
00:00:00.204268 [2562641:shadow-worker] 00:00:00.000274460 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 128, which may result in unusual behavior
00:00:00.204745 [2562641:shadow-worker] 00:00:00.000281490 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 435 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.204746 [2562641:shadow-worker] 00:00:00.000281490 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 435, which may result in unusual behavior
00:00:00.240779 [2562641:shadow-worker] 00:00:00.000301510 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 26 called from thread 1001 in process server1.mongod.1000 on host server1
00:00:00.240782 [2562641:shadow-worker] 00:00:00.000301510 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 26, which may result in unusual behavior
00:00:00.240867 [2562641:shadow-worker] 00:00:00.000302540 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 435 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.240868 [2562641:shadow-worker] 00:00:00.000302540 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 435, which may result in unusual behavior
00:00:00.271667 [2562641:shadow-worker] 00:00:00.000307510 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 26 called from thread 1001 in process server1.mongod.1000 on host server1
00:00:00.271669 [2562641:shadow-worker] 00:00:00.000307510 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 26, which may result in unusual behavior
00:00:00.271945 [2562641:shadow-worker] 00:00:00.000309550 [WARN] [server1:222.222.222.222] [syscall_handler.c:552] [syscallhandler_make_syscall] Detected unsupported syscall 435 called from thread 1000 in process server1.mongod.1000 on host server1
00:00:00.271946 [2562641:shadow-worker] 00:00:00.000309550 [ERROR] [server1:222.222.222.222] [syscall_handler.c:556] [syscallhandler_make_syscall] Returning error 38 (ENOSYS) for unsupported syscall 435, which may result in unusual behavior
00:00:00.418333 [2562641:shadow-worker] 00:00:00.000318540 [INFO] [server1:222.222.222.222] [syscall_handler.c:106] [_syscallhandler_free] handled 58 syscalls
00:00:00.418346 [2562641:shadow-worker] 00:00:00.000318540 [INFO] [server1:222.222.222.222] [syscall_handler.c:112] [_syscallhandler_free] Thread 1001 (mongod) syscall counts: {rt_sigprocmask:13, getpid:8, write:8, gettid:7, shadow_yield:6, tgkill:4, rt_sigaction:3, futex:2, openat:2, prctl:1, rseq:1, set_robust_list:1, shadow_get_shm_blk:1, sigaltstack:1}
thread 'shadow-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ESRCH', main/host/process.rs:976:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
00:00:00.418512 [2562641:shadow-worker] 00:00:00.000318540 [ERROR] [server1:222.222.222.222] [rc.rs:129] [shadow_shim_helper_rs::rootedcell::rc] Dropped without calling `safely_drop`
thread 'shadow-worker' panicked at 'assertion failed: self.shim_shmem_lock.borrow().is_none()', main/host/host.rs:821:9
thread '<unnamed>' panicked at 'A work thread panicked', main/core/scheduler/pools/unbounded.rs:192fatal runtime error: :failed to initiate panic, error 175

Aborted (core dumped)
```

MongoDB log:
```
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"TENANT_M", "id":7091600, "ctx":"main","msg":"Starting TenantMigrationAccessBlockerRegistry"}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"F",  "c":"CONTROL",  "id":23385,   "ctx":"SignalHandler","msg":"sigwaitinfo failed with error","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"F",  "c":"ASSERT",   "id":23089,   "ctx":"SignalHandler","msg":"Fatal assertion","attr":{"msgid":16781,"file":"src/mongo/util/signal_handlers.cpp","line":310}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"D2", "c":"ASIO",     "id":22592,   "ctx":"TenantMigrationBlockerNet","msg":"The NetworkInterfaceTL reactor thread is spinning up"}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"F",  "c":"ASSERT",   "id":23090,   "ctx":"SignalHandler","msg":"\n\n***aborting after fassert() failure\n\n"}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"F",  "c":"CONTROL",  "id":6384300, "ctx":"SignalHandler","msg":"Writing fatal message","attr":{"message":"\n"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"F",  "c":"CONTROL",  "id":6384300, "ctx":"SignalHandler","msg":"Writing fatal message","attr":{"message":"Got signal: 6 (Aborted).\n"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1000,"port":27017,"dbPath":"/home/user/shadow/shadow.data/hosts/server1/./db/","architecture":"64-bit","host":"server1"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"6.3.0-alpha-1134-g6a18629","gitVersion":"nogitversion","openSSLVersion":"OpenSSL 3.0.2 15 Mar 2022","modules":[],"allocator":"tcmalloc","environment":{"distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"22.04"}}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/home/user/ds-fuzzer//src/project/mongo/mongo.conf","net":{"bindIp":"222.222.222.222","ipv6":false,"maxIncomingConnections":65536,"port":27017,"unixDomainSocket":{"enabled":false},"wireObjectCheck":true},"processManagement":{"fork":false},"security":{"authorization":"disabled","javascriptEnabled":true},"storage":{"dbPath":"./db/","directoryPerDB":false,"engine":"wiredTiger"},"systemLog":{"destination":"file","logAppend":false,"logRotate":"rename","path":"./log.txt","timeStampFormat":"iso8601-local","traceAllExceptions":true,"verbosity":3}}}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"D1", "c":"NETWORK",  "id":22940,   "ctx":"initandlisten","msg":"file descriptor and connection resource limits","attr":{"hard":1048576,"soft":1048576,"conn":838860}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"D2", "c":"-",        "id":23323,   "ctx":"initandlisten","msg":"Starting periodic job {job_name}","attr":{"job_name":"CertificateExpirationMonitor"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"E",  "c":"CONTROL",  "id":31430,   "ctx":"SignalHandler","msg":"Error collecting stack trace","attr":{"error":"unw_get_proc_name(55555B40EA84): unspecified (general) error\nerror: unw_step: unspecified (general) error\nunw_get_proc_name(55555B40EA84): unspecified (general) error\nerror: unw_step: unspecified (general) error\n"}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":31380,   "ctx":"SignalHandler","msg":"BACKTRACE","attr":{"bt":{"backtrace":[{"a":"55555B40EA84","b":"555555554000","o":"5EBAA84"}],"processInfo":{"mongodbVersion":"6.3.0-alpha-1134-g6a18629","gitVersion":"nogitversion","compiledModules":[],"uname":{"sysname":"shadowsys","release":"shadowrelease","version":"shadowversion","machine":"shadowmachine"},"somap":[{"b":"555555554000","elfType":3,"buildId":"0F3A67350DF1FF6CE6D2CA2EE3A93ED740B4F4FD"}]}}},"tags":[]}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"SignalHandler","msg":"Frame","attr":{"frame":{"a":"55555B40EA84","b":"555555554000","o":"5EBAA84"}}}
{"t":{"$date":"2000-01-01T00:00:00.000+00:00"},"s":"D1", "c":"EXECUTOR", "id":23104,   "ctx":"OCSPManagerHTTP-0","msg":"Starting thread","attr":{"threadName":"OCSPManagerHTTP-0","poolName":"OCSPManagerHTTP"}}
```

Looks like the missing support of `sigwaitinfo` is the root cause for the failure at this point.

**To Reproduce**

Simulate a MongoDB server and a mongo shell.

**Operating System (please complete the following information):**

Ubuntu 22.04.

 - Kernel version: post the output of `uname -a`  

5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  

Shadow v2.3.0-268-g1056fefe 2023-01-18--18:29:56

**Comment by stevenengler** [comment]
Thanks for the bug report! There are two independent issues here. MongoDB seems to be failing due to `SYS_sigwaitinfo` not being supported, and then Shadow crashes when the MongoDB process exits. There are a bunch of other unsupported syscall warnings that may also be important.

TODO:

- [ ] Fix shadow panic in `Process::reap_thread`
- [ ] Support `SYS_sigwaitinfo`

@sporksmith The unwrap here is panicking from `ESRCH`, so the thread must not exist anymore. Should this loop and try other threads instead of panicking?

https://github.com/shadow/shadow/blob/1056fefe69bc425abec6f51b3c7e8b037c3e4a81/src/main/host/process.rs#L967-L979

**Comment by sporksmith** [comment]
> @sporksmith The unwrap here is panicking from ESRCH, so the thread must not exist anymore. Should this loop and try other threads instead of panicking?

Maybe, but I'd like to understand how that's happening.

@Congyu-Liu do you have a shadow config file for reproducing this issue?

**Comment by Congyu-Liu** [comment]
Hi @sporksmith , thanks for looking into this! Here's the configuration files I use.

Shadow config file:

```
general:
  stop_time: 30
  model_unblocked_syscall_latency: true

network:
  graph:
    type: 1_gbit_switch

experimental:
  use_preload_libc: false

hosts:
  mongosh:
    network_node_id: 0
    processes:
    - path: $PATH_TO_MONGO
      args: 222.222.222.222:27017 /home/congyu/ds-fuzzer//src/project/mongo/hello.js
      start_time: 20
  server1:
    ip_addr: 222.222.222.222
    network_node_id: 0
    processes:
    - path: $PATH_TO_MONGOD
      args: --config $PATH_TO_MONGOD_CONFIG --bind_ip 222.222.222.222
```

Mongod config file:

```
systemLog:
   verbosity: 3
   traceAllExceptions: true
   path: ./log.txt
   logAppend: false
   logRotate: rename
   destination: file
   timeStampFormat: iso8601-local

processManagement:
   fork: false

net:
   port: 27017 
   bindIp: 127.0.0.1
   maxIncomingConnections: 65536
   wireObjectCheck: true
   ipv6: false
   unixDomainSocket:
      enabled: false

security:
   authorization: disabled
   javascriptEnabled:  true

storage:
   dbPath: ./db/
   directoryPerDB: false
   engine: wiredTiger

```

**Comment by sporksmith** [comment]
Thanks! I was able to reproduce locally.

It looks like the mongodb server is aborting after the `sigwaitinfo` fails, so as expected we'll most likely have to actually implement `sigwaitinfo` for mongodb to work. Filed https://github.com/shadow/shadow/issues/2678

Here's the stack:

```
0x00007ffff742b3ee in shim_native_syscallv () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
(gdb) bt
#0  0x00007ffff742b3ee in shim_native_syscallv () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#1  0x00007ffff742c085 in shim_syscallv () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#2  0x00007ffff742c158 in shim_syscall () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#3  0x00007ffff74294c2 in _shim_seccomp_handle_sigsys () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#4  <signal handler called>
#5  0x00007ffff7729a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff76d5476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007ffff7429ae1 in _die_with_fatal_signal () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#8  0x00007ffff7429c36 in shim_process_signals () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#9  0x00007ffff742b738 in _shim_emulated_syscall_event () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#10 0x00007ffff742bddd in shim_emulated_syscallv () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#11 0x00007ffff742c024 in shim_syscallv () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#12 0x00007ffff742c158 in shim_syscall () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#13 0x00007ffff74294c2 in _shim_seccomp_handle_sigsys () from /home/jnewsome/.local/bin/../lib/../lib/libshadow-shim.so
#14 <signal handler called>
#15 0x00007ffff7729a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x00007ffff76d5476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#17 0x00007ffff76bb7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#18 0x000055555744c85a in mongo::fassertFailedWithLocation(int, char const*, unsigned int) ()
#19 0x00005555583f57ed in mongo::(anonymous namespace)::signalProcessingThread(mongo::LogFileStatus) ()
#20 0x00005555583f6679 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<mongo::stdx::thread::thread<void (*)(mongo::LogFileStatus), mongo::LogFileStatus&, 0>(void (*)(mongo::LogFileStatus), mongo::LogFileStatus&)::{lambda()#1}> > >::_M_run() ()
#21 0x000055555a4c6a7f in execute_native_thread_routine ()
#22 0x00007ffff7727b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#23 0x00007ffff77b8bb4 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

I think what's happening during teardown is that when we detect the native process has exited (via SIGABRT), we arrange to tear down all the threads in the process, but the corresponding native threads are already dead and gone. Inside `Process::reap_thread` it sees that there are other threads that haven't been torn down yet, but doesn't "know" they're already gone. I *think* we just need to mark the whole process as exiting (`Process::is_exiting`) when we detect that the process has died with a signal before we try tearing down the individual threads.

I'll fix this and add a regression test.

**Comment by sporksmith** [comment]
https://github.com/shadow/shadow/pull/2680 fixes the panic in Shadow itself.

After that, the client was hanging in a busy-loop. I filed https://github.com/shadow/shadow/issues/2681 for that issue, but here it can be worked around by removing `use_preload_libc: false` from the shadow config (is there a reason it's being used here?)

Again I think we'll need to implement `sigwaitinfo` (https://github.com/shadow/shadow/issues/2678) to actually get further in the simulation. I'm not going to dive into it right now, but I think it wouldn't be *too* bad.
