### ISSUE TITLE
Make it easier to diagnose missing managed process missing runtime deps

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#3142]
When a dynamically linked library needed by a managed process started by shadow is missing, the output in shadow's stderr is along the lines of:

```
thread 'shadow-worker' panicked at 'called `Result::unwrap()` on an `Err` value: WriterIsClosed', main/host/managed_thread.rs:133:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: shadow_rs::host::managed_thread::ManagedThread::spawn
   4: shadow_rs::host::process::Process::spawn
   5: shadow_rs::host::host::Host::add_application::{{closure}}
   6: shadow_rs::host::host::Host::execute
   7: shadow_rs::core::worker::Worker::with_active_host
   8: shadow_rs::core::scheduler::thread_per_core::HostIter<HostType>::for_each
   9: shadow_rs::core::scheduler::thread_per_core::SchedulerScope<HostType>::run_with_data::{{closure}}
  10: shadow_rs::core::scheduler::pools::unbounded::work_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'A work thread panicked', main/core/scheduler/pools/unbounded.rs:193:17
```

The above is because the managed process died (closing a pipe) before initializing the shim. We should probably catch that error and make that a little clearer.

The root cause  for *why* it died in such cases is in the shimlog, since that's where the process's stdout and stderr go before the shim is initialized:

```
../../target/x86_64-unknown-linux-gnu/debug/arti: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
```

I'm not sure how much we can do to improve this; redirecting the native stdout and stderr to the managed process's `stdout` and `stderr` files might be a little better, but might take a little care to do safely since both the shadow process and managed process would be appending to the same files.

Maybe it's sufficient if the shadow-side error includes a hint to look at the shimlog. Something like "The managed process X failed to initialize correctly; check X.shimlog for details"

**Comment by stevenengler** [comment]
> Maybe it's sufficient if the shadow-side error includes a hint to look at the shimlog. Something like "The managed process X failed to initialize correctly; check X.shimlog for details"

I think this seems nicer than redirecting the stdout/stderr of all managed processes to shadow's stdout/stderr. I feel like redirecting to shadow's stdout/stderr would make things even more confusing since none of it is guaranteed to be in order across processes and there's no context about where any of the output comes from.

Shadow could also do something fancy like log the last _n_ lines of the process' shim log (if there is anything in the shim log) so that the user doesn't need to open it themselves.

**Comment by sporksmith** [comment]
> I think this seems nicer than redirecting the stdout/stderr of all managed processes to shadow's stdout/stderr.

To be clear I wasn't proposing that - I was proposing that the native stdout and stderr go to the process's "managed" stdout and stderr files respectively instead of its shimlog.

> Shadow could also do something fancy like log the last n lines of the process' shim log (if there is anything in the shim log) so that the user doesn't need to open it themselves.

> Is there some reason you couldn't copy the stderr somewhere more obvious, at least if it's short or if you know this happened because the shim failed to start?

Yeah something along these lines might be a further quality of life improvement, but I'm a little wary about trying to be too clever here. It opens up questions about when to do this, how much to copy etc.

**Comment by sporksmith** [comment]
> To be clear I wasn't proposing that - I was proposing that the native stdout and stderr go to the process's "managed" stdout and stderr files respectively instead of its shimlog.

I guess a downside of that is that it'll be more difficult to distinguish between native and managed output in the same file.

Theoretically it might make sense to have Yet Another set of output files for native stdout and stderr, but it's probably not worth the clutter of the extra output files, which would normally be empty.

Usability-wise it might be nice if the native stdout and stderr went to a pipe read by a thread in shadow that then logged each  line with the appropriate metadata (identifying which process it came from etc), but that would be a fair bit of system complexity to add on, and use another big chunk of file descriptors on the system.

**Comment by stevenengler** [comment]
> To be clear I wasn't proposing that - I was proposing that the native stdout and stderr go to the process's "managed" stdout and stderr files respectively instead of its shimlog.

Oops sorry I read that wrong. 

> I guess a downside of that is that it'll be more difficult to distinguish between native and managed output if it's in the same file.

Yeah I agree, but this distinction might be only important to shadow developers (or people debugging something complicated in shadow) and most users probably don't care about the distinction. So maybe it would be worthwhile if it's simpler to users?

> Usability-wise it might be nice if the native stdout and stderr went to a pipe read by a thread in shadow that then logged each line with the appropriate metadata (identifying which process it came from etc), but that would be a fair bit of system complexity to add on, and use another big chunk of file descriptors on the system.

An option to limit the number of files/descriptors could be to use a Unix socket. I believe that you can use recvmsg to get the pid of the sender through auxiliary data, so you would only need a single unix socket on the shadow side. And you could maybe even share a single sending socket between all the managed processes.

**Comment by sporksmith** [comment]
> An option to limit the number of files/descriptors could be to use a Unix socket. I believe that you can use recvmsg to get the pid of the sender through auxiliary data, so you would only need a single unix socket on the shadow side. And you could maybe even share a single sending socket between all the managed processes.

Does that work even if the sending side is just using `write` syscalls?

**Comment by sporksmith** [comment]
Interesting; maybe it'd be worth doing that for the shim log too; i.e. get rid of the separate shim logs and pipe them through shadow's logging instead.
