### ISSUE TITLE
Build issue on Solus with glibc debug symbols

### ISSUE THREAD

**Issue by JRud52** [shadow/shadow#350]
I am getting this error while trying to run the build script.
 
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ ./setup build
2017-10-07 13:11:58,469 [INFO] running 'cmake /home/jrud/documents/school/thesis/shadow -DCMAKE_INSTALL_PREFIX=/home/jrud/.shadow -DCMAKE_EXTRA_INCLUDES=/home/jrud/documents/school/thesis/shadow/build;/home/jrud/.shadow/include -DCMAKE_EXTRA_LIBRARIES=/home/jrud/documents/school/thesis/shadow/build;/home/jrud/.shadow/lib' from '/home/jrud/documents/school/thesis/shadow/build'
-- The C compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- 
-- -------------------------------------------------------------------------------
-- Current settings: (change with '$ cmake -D<OPTION>=<ON|OFF>')
-- SHADOW_DEBUG=OFF
-- SHADOW_PROFILE=OFF
-- SHADOW_TEST=OFF
-- SHADOW_EXPORT=OFF
-- -------------------------------------------------------------------------------
-- 
-- CMAKE_BUILD_TYPE Release enabled.
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- CMAKE_MODULE_PATH = /home/jrud/documents/school/thesis/shadow/cmake/;/home/jrud/.shadow/include;/home/jrud/documents/school/thesis/shadow/build
-- Decompressing /home/jrud/documents/school/thesis/shadow/resource/topology.graphml.xml.xz
-- Found components for RT
-- RT_INCLUDES = /usr/include
-- RT_LIBRARIES = /usr/lib/librt.so
-- Found components for DL
-- DL_INCLUDES = /usr/include
-- DL_LIBRARIES = /usr/lib/libdl.so
-- Found components for M
-- M_INCLUDES = /usr/include
-- M_LIBRARIES = /usr/lib/libm.so
-- Found components for IGRAPH
-- IGRAPH_INCLUDES = /usr/local/include/igraph
-- IGRAPH_LIBRARIES = /usr/local/lib/libigraph.so
-- IGRAPH_VERSION_STRING_LINE = #define IGRAPH_VERSION "0.7.1"
-- IGRAPH_VERSION_MAJOR_GUESS = 0
-- IGRAPH_VERSION_MINOR_GUESS = 7
-- IGRAPH_VERSION_PATCH_GUESS = 1
-- Found components for GLIB
-- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/include/glib-2.0
-- GLIB_LIBRARIES = /usr/lib/libglib-2.0.so;/usr/lib/libgthread-2.0.so;/usr/lib/libgmodule-2.0.so
-- GLIB_MAJOR_VERSION = 
-- GLIB_MINOR_VERSION = 
-- GLIB_MICRO_VERSION = 
-- Checking for C LLVM compiler...
-- Checking for C LLVM compiler... works.
-- Checking for CXX LLVM compiler...
-- Checking for CXX LLVM compiler... works.
-- The CXX compiler identification is Clang 4.0.1
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found components for LLVM
-- LLVM_CMAKE_DIR = /usr/lib/cmake/llvm
CMake Warning (dev) at /usr/lib/cmake/llvm/AddLLVM.cmake:629 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  src/plugin/llvm-hoist-pass/CMakeLists.txt:44 (add_llvm_loadable_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/lib/cmake/llvm/AddLLVM.cmake:629 (if):
  if given arguments:

    "LLVMHoistGlobals" "IN_LIST" "LLVM_DISTRIBUTION_COMPONENTS" "OR" "NOT" "LLVM_DISTRIBUTION_COMPONENTS"

  Unknown arguments specified
Call Stack (most recent call first):
  src/plugin/llvm-hoist-pass/CMakeLists.txt:44 (add_llvm_loadable_module)


-- Configuring incomplete, errors occurred!
See also "/home/jrud/documents/school/thesis/shadow/build/CMakeFiles/CMakeOutput.log".
2017-10-07 13:12:01,380 [ERROR]  Non-zero return code from cmake.
```
CMake version:
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ cmake --version
cmake version 3.8.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
Clang version:
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-solus-linux
Thread model: posix
InstalledDir: /usr/bin
```
Distro info: 
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	3
Codename:	shannon
```
Linux version:
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ uname -srv
Linux 4.12.14-21.current #1 SMP Fri Sep 22 03:15:23 UTC 2017
```

**Comment by robgjansen** [comment]
I just released Shadow version 1.12.0. We have now removed LLVM/Clang as a component in the build process, along with a host of other improvements. Could you please try installing the latest from master? (The wiki pages have been updated to be consistent with installing v1.12.0.)

**Comment by JRud52** [comment]
OK so I pulled down a clean version of master, and this is the result now:

```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ ./setup build
2017-10-09 12:51:32,530 [INFO] running 'cmake /home/jrud/documents/school/thesis/shadow -DCMAKE_INSTALL_PREFIX=/home/jrud/.shadow -DCMAKE_EXTRA_INCLUDES=/home/jrud/documents/school/thesis/shadow/build;/home/jrud/.shadow/include -DCMAKE_EXTRA_LIBRARIES=/home/jrud/documents/school/thesis/shadow/build;/home/jrud/.shadow/lib' from '/home/jrud/documents/school/thesis/shadow/build'
-- The C compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- System name: Linux
-- System version: 4.12.14-21.current
-- System processor: x86_64
-- CMAKE_MODULE_PATH = /home/jrud/documents/school/thesis/shadow/cmake/;/home/jrud/.shadow/include;/home/jrud/documents/school/thesis/shadow/build
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- 
-- -------------------------------------------------------------------------------
-- Current settings: (change with '$ cmake -D<OPTION>=<ON|OFF>')
-- SHADOW_DEBUG=OFF
-- SHADOW_PROFILE=OFF
-- SHADOW_TEST=OFF
-- SHADOW_EXPORT=OFF
-- -------------------------------------------------------------------------------
-- 
-- CMAKE_BUILD_TYPE Release enabled.
-- Decompressing /home/jrud/documents/school/thesis/shadow/resource/topology.graphml.xml.xz
-- Found components for RT
-- RT_INCLUDES = /usr/include
-- RT_LIBRARIES = /usr/lib/librt.so
-- Found components for DL
-- DL_INCLUDES = /usr/include
-- DL_LIBRARIES = /usr/lib/libdl.so
-- Found components for M
-- M_INCLUDES = /usr/include
-- M_LIBRARIES = /usr/lib/libm.so
-- Found components for IGRAPH
-- IGRAPH_INCLUDES = /usr/local/include/igraph
-- IGRAPH_LIBRARIES = /usr/local/lib/libigraph.so
-- IGRAPH_VERSION_STRING_LINE = #define IGRAPH_VERSION "0.7.1"
-- IGRAPH_VERSION_MAJOR_GUESS = 0
-- IGRAPH_VERSION_MINOR_GUESS = 7
-- IGRAPH_VERSION_PATCH_GUESS = 1
-- Found components for GLIB
-- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/include/glib-2.0
-- GLIB_LIBRARIES = /usr/lib/libglib-2.0.so;/usr/lib/libgthread-2.0.so;/usr/lib/libgmodule-2.0.so
-- GLIB_MAJOR_VERSION = 
-- GLIB_MINOR_VERSION = 
-- GLIB_MICRO_VERSION = 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Threads library: -lpthread
-- Found components for GLIB
-- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/include/glib-2.0
-- GLIB_LIBRARIES = /usr/lib/libglib-2.0.so;/usr/lib/libgthread-2.0.so;/usr/lib/libgmodule-2.0.so
-- GLIB_MAJOR_VERSION = 
-- GLIB_MINOR_VERSION = 
-- GLIB_MICRO_VERSION = 
-- Found components for IGRAPH
-- IGRAPH_INCLUDES = /usr/local/include/igraph
-- IGRAPH_LIBRARIES = /usr/local/lib/libigraph.so
-- IGRAPH_VERSION_STRING_LINE = #define IGRAPH_VERSION "0.7.1"
-- IGRAPH_VERSION_MAJOR_GUESS = 0
-- IGRAPH_VERSION_MINOR_GUESS = 7
-- IGRAPH_VERSION_PATCH_GUESS = 1
-- Found components for DL
-- DL_INCLUDES = /usr/include
-- DL_LIBRARIES = /usr/lib/libdl.so
-- The CXX compiler identification is GNU 6.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found components for RT
-- RT_INCLUDES = /usr/include
-- RT_LIBRARIES = /usr/lib/librt.so
-- Found components for M
-- M_INCLUDES = /usr/include
-- M_LIBRARIES = /usr/lib/libm.so
-- Found components for IGRAPH
-- IGRAPH_INCLUDES = /usr/local/include/igraph
-- IGRAPH_LIBRARIES = /usr/local/lib/libigraph.so
-- IGRAPH_VERSION_STRING_LINE = #define IGRAPH_VERSION "0.7.1"
-- IGRAPH_VERSION_MAJOR_GUESS = 0
-- IGRAPH_VERSION_MINOR_GUESS = 7
-- IGRAPH_VERSION_PATCH_GUESS = 1
-- Found components for GLIB
-- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/include/glib-2.0
-- GLIB_LIBRARIES = /usr/lib/libglib-2.0.so;/usr/lib/libgthread-2.0.so;/usr/lib/libgmodule-2.0.so
-- GLIB_MAJOR_VERSION = 
-- GLIB_MINOR_VERSION = 
-- GLIB_MICRO_VERSION = 
-- CMAKE_C_FLAGS = -g2 -O3 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fexceptions -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -O3 -Wno-unknown-attributes -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-invalid-noreturn -fPIC -std=gnu11 -fno-inline -fno-strict-aliasing -U_FORTIFY_SOURCE
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- System version: 4.12.14-21.current
-- Architecture: x86_64
-- LDSO = /lib64/ld-linux-x86-64.so.2
-- LIBDL = 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jrud/documents/school/thesis/shadow/build
2017-10-09 12:51:35,642 [INFO] calling make -j1
Scanning dependencies of target vdlconfig
[  1%] Generating vdl-config.h
Traceback (most recent call last):
  File "/home/jrud/documents/school/thesis/shadow/src/external/elf-loader/extract-system-config.py", line 268, in <module>
    main(sys.argv[1:])
  File "/home/jrud/documents/school/thesis/shadow/src/external/elf-loader/extract-system-config.py", line 207, in main
    debug_filename = search_debug_file ()
  File "/home/jrud/documents/school/thesis/shadow/src/external/elf-loader/extract-system-config.py", line 166, in search_debug_file
    raise CouldNotFindFile ()
__main__.CouldNotFindFile: <__main__.CouldNotFindFile instance at 0x7f002f2d8a70>
make[2]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:61: src/external/elf-loader/vdl-config.h] Error 1
make[2]: *** Deleting file 'src/external/elf-loader/vdl-config.h'
make[1]: *** [CMakeFiles/Makefile2:711: src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
2017-10-09 12:51:35,703 [ERROR] Non-zero return code from make.

```

**Comment by jtracey** [comment]
What linux distro (including version) are you using?

**Comment by JRud52** [comment]
Distro info: 
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	3
Codename:	shannon
```
Linux version:
```
jrud@solus_thinkpad ~/documents/school/thesis/shadow $ uname -srv
Linux 4.12.14-21.current #1 SMP Fri Sep 22 03:15:23 UTC 2017
```

**Comment by jtracey** [comment]
I don't know much about Solus, but it looks like it either doesn't come with glibc debug symbols or they're not stored in at a standard path. Do you happen to know how debug symbols work for Solus?

The cmake script is also not detecting version info for glib and can't find libdl. I would guess that those will have to be fixed too, but maybe it will work without it.

**Comment by JRud52** [comment]
both the glibc and glib2 debug info packages are installed on my system. I'm not sure where the standard paths for those files are though.

**Comment by jtracey** [comment]
It should be in a directory like /usr/lib/debug. If you find a directory like that, cd to it and try running
`find -name "ld-*"`

**Comment by JRud52** [comment]
It looks like the debug directories exist, but there is nothing in them except for a .build-id directory. I am not sure where the ld files have ended up.

**Comment by JRud52** [comment]
Looks like there is an ld-linux-x86-64.so.2 and ld-2.25.so in the `/usr/lib` directory

**Comment by jtracey** [comment]
Yeah, those are the shared objects themselves, not the debug files. What is in the .build-id directory? I'm a bit confused how gdb finds debug symbols if the debug files aren't there...

**Comment by JRud52** [comment]
The .build-id directory just has a bunch of weirdly named files:

```
jrud@solus_thinkpad /usr/lib/debug/.build-id $ ls
01  09  12  19  20  2b  35  43  4e  59  5f  69  70  78  80  87  91  97  a2  a9  af  b6  bf  c8  d1  d7  e1  ea  f0  f8
03  0a  13  1a  21  2c  36  44  50  5a  62  6a  71  7b  81  88  92  98  a3  aa  b0  b9  c0  c9  d2  d9  e2  eb  f2  f9
04  0b  14  1b  22  2e  39  45  53  5b  64  6b  72  7c  82  89  93  9b  a4  ab  b2  ba  c2  ca  d3  da  e4  ec  f4  fb
05  0e  15  1c  24  2f  3d  46  55  5c  65  6c  74  7d  83  8c  94  9d  a6  ac  b3  bc  c3  cc  d4  db  e5  ed  f5  fc
06  10  16  1d  26  31  3e  4a  56  5d  67  6e  75  7e  85  8e  95  9f  a7  ad  b4  bd  c4  cd  d5  dd  e7  ee  f6  fe
07  11  17  1e  29  34  42  4c  57  5e  68  6f  77  7f  86  90  96  a0  a8  ae  b5  be  c6  cf  d6  de  e8  ef  f7  ff
jrud@solus_thinkpad /usr/lib/debug/.build-id $ ls -la
total 728
drwxr-xr-x 182 root root 4096 Oct  9 15:28 .
drwxr-xr-x   3 root root 4096 Oct 10 18:16 ..
drwxr-xr-x   2 root root 4096 Oct 10 17:37 01
drwxr-xr-x   2 root root 4096 Oct 10 17:37 03
drwxr-xr-x   2 root root 4096 Oct 10 17:37 04
drwxr-xr-x   2 root root 4096 Oct 10 17:37 05
drwxr-xr-x   2 root root 4096 Oct 10 17:37 06
drwxr-xr-x   2 root root 4096 Oct 10 17:37 07
...
```

**Comment by robgjansen** [comment]
@JRud52 Can you try adding `find_build_id(/usr/lib64/ld-2.25.so)` following this line:
https://github.com/shadow/shadow/blob/8e1c300f68ca8c7d243535387a9c86c566347530/src/external/elf-loader/extract-system-config.py#L179

and check if that fixes things for you on Solus? Thanks for all the help in fixing and testing this issue!

**Comment by JRud52** [comment]
It looks like it is finding the debug symbols when I add this below:
``` python
# Solus
find_build_id('/usr/lib/ld-2.25.so'),
```

I also noticed that the `find_build_id` function should have a check to see if the file was opened or not. I fixed this by adding 

``` python
if not file:
   return None 
```
after the `file = os.popen('readelf -n {}'.format(path), 'r')` on line 10

**Comment by robgjansen** [comment]
The error you posted says this:

```
readelf: Error: '/lib/x86_64-linux-gnu/ld-2.24.so': No such file
readelf: Error: '/lib/i386-linux-gnu/ld-2.24.so': No such file
```

Why is it looking for `ld-2.24.so`? Shouldn't it be finding `ld-2.25.so` since you added `find_build_id('/usr/lib/ld-2.25.so'),`?

**Comment by JRud52** [comment]
It is finding ld-2.25.so, but since the `find_build_ids` method is called before that for ld-2.24.so for Debian 9. Line 10: `file = os.popen('readelf -n {}'.format(path), 'r')` will produce an error if you are not using Debian 9 and it cannot find those files. Since the line I added below that did not produce an error, that means it found the file and was able to open it.

**Comment by jtracey** [comment]
That's the path for Debian, if I'm understanding the package manager files correctly (see https://packages.solus-project.com/shannon/g/glibc/ ), you should try using `find_build_id(/usr/lib64/ld-2.25.so)`

**Comment by robgjansen** [comment]
I installed Solus Budgie on a VM and corrected the search for `ld-2.25.so` in ffe880f638e7e2ced04fcdbdde80f84c3693ab6d.

The next error is:

```
Scanning dependencies of target vdlconfig
[  2%] Generating vdl-config.h
Traceback (most recent call last):
  File "/home/rob/shadow/src/external/elf-loader/extract-system-config.py", line 295, in <module>
    main(sys.argv[1:])
  File "/home/rob/shadow/src/external/elf-loader/extract-system-config.py", line 256, in main
    data = debug.get_struct_member_offset ('rtld_global', '_dl_error_catch_tsd')
  File "/home/rob/shadow/src/external/elf-loader/extract-system-config.py", line 122, in get_struct_member_offset
    return self.find_member (member_name, item)
  File "/home/rob/shadow/src/external/elf-loader/extract-system-config.py", line 108, in find_member
    self.write_back_one ()
TypeError: write_back_one() takes exactly 2 arguments (1 given)
make[2]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:61: src/external/elf-loader/vdl-config.h] Error 1
make[2]: *** Deleting file 'src/external/elf-loader/vdl-config.h'
make[1]: *** [CMakeFiles/Makefile2:721: src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
2017-10-18 10:29:48,749 [ERROR] Non-zero return code from make.
```

**Comment by robgjansen** [comment]
If I pass in `sub_item` or `parent` in to `write_back_one ()` here:

https://github.com/shadow/shadow/blob/ffe880f638e7e2ced04fcdbdde80f84c3693ab6d/src/external/elf-loader/extract-system-config.py#L107-L109

Then the `data` variable here is `None` and the script exits.

https://github.com/shadow/shadow/blob/ffe880f638e7e2ced04fcdbdde80f84c3693ab6d/src/external/elf-loader/extract-system-config.py#L256-L259

I'm not actually sure what the correct fix is. Is this because `rtld_global` is no longer supported?

**Comment by jtracey** [comment]
No, it appears _dl_error_catch_tsd was removed:
https://sourceware.org/git/?p=glibc.git;a=blob;f=ChangeLog.old/ChangeLog.18;h=b0c91453ae1c99505f318ed1d316e1d975f9e395;hb=HEAD#l13973

It looks like we'll have to modify the python script to allow it to not be set, then modify https://github.com/shadow/shadow/blob/ffe880f638e7e2ced04fcdbdde80f84c3693ab6d/src/external/elf-loader/glibc.c#L223
to not write if that offset isn't set. It looks like there's been a change in the way dl errors are handled. Hopefully it doesn't affect us; a cursory glance says all the affected functions are ones we replace in elf-loader anyway, but I'll take a closer look at that commit.

**Comment by robgjansen** [comment]
OK, let me know when I should test something on my Solus VM.

**Comment by JRud52** [comment]
I can also test changes as they come. I don't know too much about the linux debug symbol stuff, so I likely won't be much help in figuring out how to fix the issue.

**Comment by jtracey** [comment]
Quick update: I believe I've fixed the solus-specific issues in https://github.com/jtracey/shadow/tree/solus

But testing it in a VM, it looks like there are still problems because of changes in glibc. I'm currently installing Ubuntu 17.10, which uses glibc 2.26, so that I can debug any issues on that, then come back to this (hopefully the bugs from upgrading to 2.26 are a superset of the bugs from upgrading to 2.25).

**Comment by JRud52** [comment]
Has there been any progress with fixing the glibc ^2.25 issue?

**Comment by jtracey** [comment]
It's been on my back burner, but yes, progress is being made.

**Comment by jtracey** [comment]
I've pushed the latest fixes to the git branch on my fork, and it works on my Solus VM. I can't upstream it here yet because the changes break older versions of glibc, but if you need something now feel free to use that branch in the meantime.

**Comment by JRud52** [comment]
Thanks for getting this fixed. Works great now!
