### ISSUE TITLE
Occasional crashes in igraph call to realloc

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#798]
**Describe the issue**

We occasionally get test failures with the last line of the Shadow output:

```
realloc(): invalid pointer
```

**To Reproduce**

I've mostly been seeing this in the CI action on GitHub. After some experimentation I was able to reproduce locally by running the tcp tests in a loop until one failed:

```
$ while ctest -R tcp -j8 --output-on-failure; do :; done
```

**Operating System (please complete the following information):**

Ubuntu 18.04.4 LTS
Linux vusiri 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**

Shadow v1.13.2-606-g469dac93-dirty 2020-05-11 (built 2020-05-11) running GLib v2.56.4 and IGraph v0.7.1

**Additional context**

I tried inspecting a core file from the crash, but the symbols were missing. I tried using `vdl_linkmap_abi_update` to load the symbols, but that only works on a running process.

I was able to get a backtrace by installing a signal handler for SIGABRT to raise SIGSTOP, allowing me to attach to the running process when I hit the failure.

Patch:
```
diff --git a/src/main/core/main.c b/src/main/core/main.c
index 5ca7a1be..b1ca236d 100644
--- a/src/main/core/main.c
+++ b/src/main/core/main.c
@@ -9,6 +9,7 @@
 #endif
 #include <dlfcn.h>
 #include <elf.h>
+#include <errno.h>
 #include <glib.h>
 #include <igraph_version.h>
 #include <link.h>
@@ -731,7 +732,14 @@ static gint _main_helper(Options* options) {
     return returnCode;
 }
 
+static void _stop_for_debug(int i) {
+    fprintf(stderr, "Caught signal %d, stopping for debugger\n", i);
+    raise(SIGSTOP);
+}
+
 gint main_runShadow(gint argc, gchar* argv[]) {
+
+
     /* check the compiled GLib version */
     if (!GLIB_CHECK_VERSION(2, 32, 0)) {
         g_printerr("** GLib version 2.32.0 or above is required but Shadow was compiled against version %u.%u.%u\n",
@@ -755,6 +763,18 @@ gint main_runShadow(gint argc, gchar* argv[]) {
         return EXIT_FAILURE;
     }
 
+    const struct sigaction action = {
+        .sa_handler = _stop_for_debug,
+    };
+    if (sigaction(SIGABRT, &action, NULL) != 0) {
+        g_printerr("sigaction: %s", strerror(errno));
+        return EXIT_FAILURE;
+    }
+    if (sigaction(SIGSEGV, &action, NULL) != 0) {
+        g_printerr("sigaction: %s", strerror(errno));
+        return EXIT_FAILURE;
+    }
+
     /* parse the options from the command line */
     gchar* cmds = g_strjoinv(" ", argv);
     gchar** cmdv = g_strsplit(cmds, " ", 0);
```

gdb commands after attaching:
```
set scheduler-locking on
set unwindonsignal on
p vdl_linkmap_abi_update()
bt
```

gdb output:
```
#0  vdl_linkmap_abi_update ()
    at /home/jnewsome/projects/shadow/src/external/elf-loader/vdl-linkmap.c:104
#1  <function called from gdb>
#2  0x00007f14ef274705 in raise (sig=19) at ../sysdeps/unix/sysv/linux/raise.c:46
#3  0x0000563cda134d5a in _stop_for_debug (i=6)
    at /home/jnewsome/projects/shadow/src/main/core/main.c:737
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#6  0x00007f14edb64801 in __GI_abort () at abort.c:79
#7  0x00007f14edbad897 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7f14edcdab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#8  0x00007f14edbb490a in malloc_printerr (
    str=str@entry=0x7f14edcd8efd "realloc(): invalid pointer") at malloc.c:5350
#9  0x00007f14edbbceba in __GI___libc_realloc (oldmem=0x7f14e829e960 <director>, bytes=128)
    at malloc.c:3174
#10 0x00007f14e8082d2f in realloc (a=0x7f14e829e960 <director>, b=128)
    at /home/jnewsome/projects/shadow/src/preload/preload_defs.h:10
#11 0x00007f14ee8ff46f in igraph_vector_int_reserve ()
   from /usr/lib/x86_64-linux-gnu/libigraph.so.0
#12 0x00007f14ee917e95 in igraph_i_graphml_sax_handler_start_document ()
   from /usr/lib/x86_64-linux-gnu/libigraph.so.0
#13 0x00007f14ed7b98f7 in ?? () from /usr/lib/x86_64-linux-gnu/libxml2.so.2
#14 0x00007f14ed7ba5de in xmlParseChunk () from /usr/lib/x86_64-linux-gnu/libxml2.so.2
#15 0x00007f14ee91a331 in igraph_read_graph_graphml ()
   from /usr/lib/x86_64-linux-gnu/libigraph.so.0
#16 0x0000563cda16b2ca in _topology_loadGraph (top=0x563cdaa39ef0, 
    graphPath=0x563cdaa3c270 "/tmp/shadow-topology-3H6OK0.graphml.xml")
    at /home/jnewsome/projects/shadow/src/main/routing/topology.c:386
#17 0x0000563cda172db7 in topology_new (
    graphPath=0x563cdaa3c270 "/tmp/shadow-topology-3H6OK0.graphml.xml")
    at /home/jnewsome/projects/shadow/src/main/routing/topology.c:2502
#18 0x0000563cda135852 in _master_loadTopology (master=0x563cdaa315a0)
    at /home/jnewsome/projects/shadow/src/main/core/master.c:224
#19 0x0000563cda136441 in master_run (master=0x563cdaa315a0)
    at /home/jnewsome/projects/shadow/src/main/core/master.c:407
#20 0x0000563cda134c9a in _main_helper (options=0x563cdaa2dd30)
    at /home/jnewsome/projects/shadow/src/main/core/main.c:724
#21 0x0000563cda134ff9 in main_runShadow (argc=7, argv=0x7ffea57526c8)
    at /home/jnewsome/projects/shadow/src/main/core/main.c:811
#22 0x0000563cda176176 in main (argc=7, argv=0x7ffea57526c8)
    at /home/jnewsome/projects/shadow/src/main/main.c:10
```

**Comment by stevenengler** [comment]
We've removed the igraph dependency from shadow, so will not be an issue anymore.
