### ISSUE TITLE
Segementation fault when logging ram usage

### ISSUE THREAD

**Issue by Smeat** [shadow/shadow#800]
**Describe the issue**
When running with the option "-i ram", shadow crashes with a segmentation fault during/after shutdown.
"node" and "socket" are working.

**To Reproduce**
Follow the readme to install shadow and tgen. Run the example in "resource/examples" with 

`shadow -i ram shadow.config.xml`

**Operating System (please complete the following information):**
Debian GNU/Linux 10 (buster)
Linux debian 4.19.0-9-amd64 1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

Fresh install. Only installed packages from the readme.

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v1.13.2-608-g035872e6 2020-05-11 (built 2020-05-12) running GLib v2.58.3 and IGraph v0.7.1
 - Which plug-ins you are using:  
tgen v1.0.0

**Additional context**
Output:

```
[..]
00:00:22.514973 [thread-0] 00:59:59.000000000 [message] [server~11.0.0.1] [tracker.c:560] [_tracker_logRAM] [shadow-heartbeat] [ram] 1,37123,37123,321864,143,0
00:00:22.514980 [thread-0] 00:59:59.000000000 [message] [client~11.0.0.2] [tracker.c:560] [_tracker_logRAM] [shadow-heartbeat] [ram] 1,0,0,318083,87,100
00:00:22.515097 [thread-0] n/a [message] [n/a] [scheduler.c:108] [_scheduler_stopHosts] starting to shut down 2 hosts
00:00:22.515101 [thread-0] n/a [message] [server~11.0.0.1] [process.c:1301] [process_stop] terminating main thread of process 'server.tgen.1000'
00:00:22.515104 [thread-0] n/a [message] [server~11.0.0.1] [process.c:887] [_process_executeCleanup] cleaning up process 'server.tgen.1000': aborting 0 auxiliary threads and calling 1 atexit functions
00:00:22.515350 [thread-0] n/a [message] [server~11.0.0.1] [host.c:319] [host_shutdown] host 'server' has been shut down, total execution time was 10.544271 seconds
00:00:22.515473 [thread-0] n/a [message] [client~11.0.0.2] [host.c:319] [host_shutdown] host 'client' has been shut down, total execution time was 10.845080 seconds
00:00:22.515477 [thread-0] n/a [message] [n/a] [scheduler.c:110] [_scheduler_stopHosts] 2 hosts are shut down
00:00:22.515482 [thread-0] n/a [message] [n/a] [master.c:441] [master_run] log message buffering is disabled during cleanup
00:00:22.515485 [thread-0] n/a [message] [n/a] [master.c:445] [master_run] simulation finished, cleaning up now
00:00:22.515496 [thread-0] n/a [message] [n/a] [scheduler.c:234] [scheduler_shutdown] scheduler is shutting down now
00:00:22.515499 [thread-0] n/a [message] [n/a] [scheduler.c:244] [scheduler_shutdown] waiting for 0 worker threads to finish
00:00:22.515506 [thread-0] n/a [message] [n/a] [scheduler.c:315] [_scheduler_free] 0 worker threads finished
00:00:22.515523 [thread-0] n/a [message] [n/a] [slave.c:240] [slave_free] ObjectCounter: counter values: task_new=755638 task_free=755638 event_new=755638 event_free=755638 packet_new=518009 packet_free=518009 payload_new=155136 payload_free=155136 router_new=2 router_free=2 host_new=2 host_free=2 netiface_new=4 netiface_free=4 process_new=2 process_free=2 descriptor_new=105128 descriptor_free=105128 channel_new=4 channel_free=4 tcp_new=201 tcp_free=201 udp_new=0 udp_free=0 epoll_new=6 epoll_free=6 timer_new=104917 timer_free=104917 
00:00:22.515529 [thread-0] n/a [message] [n/a] [slave.c:241] [slave_free] ObjectCounter: counter diffs: task=0 event=0 packet=0 payload=0 router=0 host=0 netiface=0 process=0 descriptor=0 channel=0 tcp=0 udp=0 epoll=0 timer=0 
00:00:22.515546 [thread-0] n/a [message] [n/a] [topology.c:1280] [_topology_clearCache] path cache cleared, spent 0.000000 seconds computing 0 shortest paths with dijkstra, and 0.000000 seconds computing 0 shortest self paths
00:00:22.515568 [thread-0] n/a [message] [n/a] [master.c:130] [master_free] simulation master destroyed
00:00:22.515571 [thread-0] n/a [message] [n/a] [main.c:730] [_main_helper] Shadow v1.13.2-608-g035872e6 2020-05-11 (built 2020-05-12) simulation was shut down cleanly, returning code 0
00:00:22.515632 [thread-0] n/a [message] [n/a] [shadow_logger.c:340] [_logger_logShutdownMessage] logging system stopped at 2020-05-12 23:27:01, run time was 00:00:22
[Thread 0x7ffff460c700 (LWP 11397) exited]
** Stopping Shadow, returning code 0 (success)

Thread 1 "shadow" received signal SIGSEGV, Segmentation fault.
0x00007ffff06cbd4c in ?? ()
(gdb) bt
#0  0x00007ffff06cbd4c in ?? ()
#1  0x00007fffffffe0e0 in ?? ()
#2  0x00007ffff3646260 in ?? ()
#3  0x00007fffffffe130 in ?? ()
#4  0x00007ffff7a19718 in _nl_current_default_domain () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000000000000001b in ?? ()
#6  0x00007ffff06cbf5a in ?? ()
#7  0x0000000000000001 in ?? ()
#8  0x00007ffff7fe80fa in call_fini (file=<error reading variable: Cannot access memory at address 0xffffffffffffffc9>)
    at /home/kevin/shadow/src/external/elf-loader/vdl-fini.c:37
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Backtrace when I load the python code from the readme:

```
#0  0x00007ffff06cbd4c in ?? () from /lib/x86_64-linux-gnu/libgfortran.so.5
#1  0x00007ffff06cbf5a in ?? () from /lib/x86_64-linux-gnu/libgfortran.so.5
#2  0x00007ffff7fe80fa in call_fini (file=0x7ffff0770810) at /home/kevin/shadow/src/external/elf-loader/vdl-fini.c:37
#3  0x00007ffff7fea562 in vdl_list_iterate (list=0x7ffff03e0670, iterator=0x7ffff7fe7fc9 <call_fini>)
    at /home/kevin/shadow/src/external/elf-loader/vdl-list.c:511
#4  0x00007ffff7fe820c in vdl_fini_call (files=0x7ffff03e0670) at /home/kevin/shadow/src/external/elf-loader/vdl-fini.c:82
#5  0x00007ffff7fe4b79 in stage2_finalize () at /home/kevin/shadow/src/external/elf-loader/stage2.c:420
#6  0x00007ffff7fe3cc2 in stage1_finalize () at /home/kevin/shadow/src/external/elf-loader/stage1.c:218
#7  0x00007ffff7897d8c in __run_exit_handlers (status=0, listp=0x7ffff7a19718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#8  0x00007ffff7897eba in __GI_exit (status=<optimized out>) at exit.c:139
#9  0x00007ffff78820a2 in __libc_start_main (main=0x5555555b8c14 <main>, argc=5, argv=0x7fffffffe308, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2f8) at ../csu/libc-start.c:342
#10 0x000055555556973a in _start ()

```

**Comment by robgjansen** [comment]
Thanks for reporting!

It appears that some valid memory information is being logged before the error occurs. This option is not on by default, and I must admit that we don't use it very often which is probably why this bug happened.

This also makes me realize that it would be useful to have our CI sweep some some non-default values for the Shadow options to help catch errors like this.
